theme: jekyll-theme-midnight
highlight: rouge

title: Random Adventures Through Infosec
description: For those breaking into the industry and seasoned veterans alike
author: 0xdeadbeefJERKY

gems:
  - jekyll-redirect-from

jekyll-crosspost_to_medium:
  enabled: true
  cache: .jekyll-crosspost_to_medium
  status: draft
  license: all-rights-reserved
  