# Site Configuration

baseurl: ''
lang: en
timezone: America/New_York

title: 0xdeadbeefJERKY Blog
tagline: Random thoughts and adventures of an offensive security engineer

description: >-
  A cybersecurity blog with a specific focus on offensive security tailored for both
  those breaking into the industry and veterans alike.

url: 'https://0xdeadbeefjerky.github.io'

github:
  username: 0xdeadbeefJERKY

twitter:
  username: 0xdeadbeefJERKY

social:
  name: Dominic Spinosa
  email: dominic@0xdeadbeefJERKY.com
  links:
    - https://twitter.com/0xdeadbeefJERKY
    - https://github.com/0xdeadbeefJERKY

google_analytics:
  id: 'G-ZR528R3VBP'

avatar: /assets/img/mehome.jpg
toc: true
paginate: 10

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      toc: true
      permalink: /posts/:title/
      image: /assets/img/og-default.png
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json
  - CLAUDE.md

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-feed